---
name: language-thrift-examples
version: 0.1.0.0
license: BSD3
author: Abhinav Gupta
maintainer: Abhinav Gupta <mail@abhinavg.net>

dependencies:
  - base
  - ansi-wl-pprint
  - language-thrift

executables:
  reformatIDL:
    main: reformatIDL.hs
  generateHaskellTypes:
    main: generateHaskellTypes.hs
    dependencies:
      - text
